#!/usr/bin/env python
# coding: utf-8

# In[1]:


# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT

"""
7-adic Prime Chain Discovery Script B (Survival)
Author: Hiroshi Harada
Date: March 5, 2026
License: MIT

This script performs a search for prime chains generated by the 7-adic mapping:

    f(n) = (8n ± k) / 7

The constant k is selected based on n mod 7 to ensure the result is an odd integer.
This parity-correcting logic avoids even-number traps and supports geometric growth.

Dependencies:
- Python 3.6+
- sympy

To install dependencies:
    pip install sympy

To run the full search:
    python hunt_7adic_survival.py
"""

import time
from sympy import isprime

def get_next_7adic_step_survival(n):
    """
    Computes the next value in the 7-adic prime chain using:
        f(n) = (8n + k) / 7
    where k is chosen based on n mod 7 to ensure the result is an odd integer.
    This version enforces odd k-values to avoid parity traps.
    """
    rem = n % 7

    # Forced odd k-values based on n mod 7
    if rem == 1:
        k = -1
    elif rem == 2:
        k = +5
    elif rem == 3:
        k = -3
    elif rem == 4:
        k = +3
    elif rem == 5:
        k = -5
    elif rem == 6:
        k = +1
    else:
        return None  # rem == 0 → 8n divisible by 7 → skip

    numerator = 8 * n + k
    if numerator % 7 != 0:
        return None  # Sanity check

    return numerator // 7

def find_7adic_chains_survival(limit, min_length=7):
    print(f"=== 7-adic 'Survival Mode' Hunt ===")
    print(f"[*] Mapping: f(n) = (8n + k) / 7  [Forced odd k]")
    print(f"[*] Search Range: 3 to {limit:,}")
    print(f"[*] Target Chain Length: {min_length} or more")
    print("=" * 35)

    start_time = time.time()
    found = 0

    for n in range(3, limit, 2):
        if not isprime(n):
            continue

        chain = [n]
        current = n

        while True:
            nxt = get_next_7adic_step_survival(current)
            if nxt is None or nxt <= current:
                break
            if isprime(nxt):
                chain.append(nxt)
                current = nxt
            else:
                break

        if len(chain) >= min_length:
            found += 1
            print(f"[✓] L{len(chain)} chain found at n₀ = {n}")
            print("    " + " → ".join(str(p) for p in chain))

    elapsed = time.time() - start_time
    print("=" * 35)
    print(f"Search complete in {elapsed:.2f} seconds.")
    print(f"Total chains of length ≥ {min_length}: {found}")

if __name__ == "__main__":
    find_7adic_chains_survival(100_000_000, min_length=7)


# In[ ]:




